@url_dev=http://localhost:3056/v1/api/
### signup

POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: 118250469218332d13806b8e2bb3c8bad5de7fbeaab7a9504ebb13607d7ddc0b774fc618af3a88c653f7ae5f0fd2aba9e3f1ba4a0e1e22be46181fab667387b9

{
    "name": "Shop TIPS",
    "email": "shoptipjs02@gmail.com",
    "password": "abc123"
}